---
# tasks file for peerau.ssh_banner
- name: Create /etc/motd+issue generator
  copy: src=generate.sh dest=/etc/banner.sh mode=o+x

- name: Create crontab entry for motd and issue
  cron: 
    name: "update motd+issue"
    job: "/etc/banner.sh"

- name: Restart sshd
  service:
    name: ssh
    state: restarted
